### PR TITLE
Update futex wake to wake multiple waiters.

### PR DESCRIPTION
**Pull request by plafratt**
Update futex wake to wake all waiters instead of just one. Issue #2319.

### CODE REVIEW

**Review by mjleven — CHANGES_REQUESTED** [review]
I believe you are waking all waiters. The futex man page says to wake "val" number of waiters. This is typically 1 or INT_MAX but could be some value in between.

**Comment by plafratt** [comment]
> I believe you are waking all waiters. The futex man page says to wake "val" number of waiters. This is typically 1 or INT_MAX but could be some value in between.

Thank you for pointing this out. I'd forgotten to cover that part of the specification.

I have a meeting tonight to prepare for, but I will try to address this tomorrow.

Thanks Again,
Patrick

**Comment by berquist** [comment]
Apologies for the delay, we were trying to understand some new CI strangeness.

**Comment by plafratt** [comment]
> Apologies for the delay, we were trying to understand some new CI strangeness.

No worries - thank you for the updates!

**Pull request merged**
