### PR TITLE
Modified Osseous for vecshift example and added missing files

### PR DESCRIPTION
**Pull request by shubhamn94**
Erase this information and put your Pull Request comments here 
---

Instructions for Issuing a Pull Request to sst-elements
-------------------------------------------------------

1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-elements

2 - Verify that Source branch is up to date with the devel branch of sst-elements

3 - After submitting your Pull Request:
   * Automatic Testing will commence in a short while 
      * Pull Requests will be tested with the devel branches of the sst-core and sst-sqe repositories
         * These branches are syncronized with the devel branch of sst-elements.  This is why is it important to keep your source branch up to date.
      * If testing passes, the source branch will be automatically merged (if possible)
         * Pull Requests from forks will not be automatically tested until the code is inspected.
         * Pull Requests from forks will not be automatically merged into the devel branch.
      * If testing fails, You will be notified of the test results.  
         * The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct problems
         
4 - DO NOT DELETE THE BRANCH (OR FORKED REPO) UNTIL THE PULL REQUEST IS MERGED.
----

### CODE REVIEW

**Comment by gvoskuilen** [comment]
@shubhamn94 Can you resolve the merge conflict?

**Review by gvoskuilen — APPROVED** [review]

**Comment by gvoskuilen** [comment]
@shubhamn94 This is a compile error on Mac:
```sh
 In file included from rtlcomponent.cc:18:
 In file included from ./rtlcomponent.h:25:
 ./rtl_header.h:68:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
         printf("\nio_out: %"PRIu8, io_out);
                             ^
                              
 ./rtl_header.h:68:36: warning: format specifies type 'unsigned char' but the argument has type 'UInt<4>' [-Wformat]
         printf("\nio_out: %"PRIu8, io_out);
                           ~~~~~~~  ^~~~~~
 1 warning and 1 error generated.
```

**Review by gvoskuilen — APPROVED** [review]

**Review by gvoskuilen — APPROVED** [review]
Thanks @shubhamn94 !

**Comment by hughes-c** [comment]
In file included from rtlevent.cc:20:
./rtl_header.h:62:23: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
    std::stringstream str;

**Comment by shubhamn94** [comment]
Fixed the error  "./rtl_header.h:62:23: error: implicit instantiation of undefined template 'std::basic_stringstream'"

**Comment by hughes-c** [comment]
Still getting this error:
```
./rtl_header.h:63:23: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
    std::stringstream str;
```

**Comment by gvoskuilen** [comment]
@shubhamn94 
I can compile on Mac if I add sstream. Here is the git diff. Can you also remove the sst_config.h includes? That header is not guarded and it shouldn't be included in another header. 
```
 #include <iostream>
+#include <sstream>        // ADD this is the missing include
 #include <inttypes.h>
 #include <array>
 #include <cstdint>
 #include <uint.h>
 #include <string.h>
 #include <sint.h>
-#include <sst/core/sst_config.h> // REMOVE 
-#include "sst_config.h"          // REMOVE
```

**Comment by shubhamn94** [comment]
Fixed 'rtl_header.h' as suggested

**Review by gvoskuilen — APPROVED** [review]

**Pull request merged**
