### PR TITLE
Cram sim address hash upgrade

### PR DESCRIPTION
**Pull request by mbhealy**
Added advanced address hashing support to CramSim. Also updated the config files and README a bit.

### CODE REVIEW

**Comment by allevin** [comment]
Failing due to a compile failure

libtool: compile:  /usr/bin/g++ -DHAVE_CONFIG_H -I. -I../../../../../sst-elements/src/sst/elements/CramSim -I../../../../src -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/local/module-pkgs/boost/boost-1.56.0-nompi_gcc-4.8.3/include -I/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/local/sst-core/include/sst/core -I/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/local/sst-core/include -g -O2 -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -MT c_BankStateActivating.lo -MD -MP -MF .deps/c_BankStateActivating.Tpo -c ../../../../../sst-elements/src/sst/elements/CramSim/c_BankStateActivating.cpp  -fPIC -DPIC -o .libs/c_BankStateActivating.o
../../../../../sst-elements/src/sst/elements/CramSim/c_AddressHasher.cpp: In constructor 'c_AddressHasher::c_AddressHasher(SST::Params&)':
../../../../../sst-elements/src/sst/elements/CramSim/c_AddressHasher.cpp:78:51: error: no matching function for call to 'regex_replace(std::string&, std::regex&, const char [1])'
     l_mapCopy = regex_replace(l_mapCopy,l_regex,""); // remove the matched portion
                                                   ^
../../../../../sst-elements/src/sst/elements/CramSim/c_AddressHasher.cpp:78:51: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../../../sst-elements/src/sst/elements/CramSim/c_AddressHasher.cpp:34:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
../../../../../sst-elements/src/sst/elements/CramSim/c_AddressHasher.cpp:78:51: note:   deduced conflicting types for parameter '_Bi_iter' ('std::basic_regex<char>' and 'const char*')
     l_mapCopy = regex_replace(l_mapCopy,l_regex,""); // remove the matched portion
                                                   ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../../../sst-elements/src/sst/elements/CramSim/c_AddressHasher.cpp:34:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
../../../../../sst-elements/src/sst/elements/CramSim/c_AddressHasher.cpp:78:51: note:   mismatched types 'const std::basic_string<_Ch_type>' and 'const char [1]'
     l_mapCopy = regex_replace(l_mapCopy,l_regex,""); // remove the matched portion
                                                   ^
depbase=`echo c_BankStateActive.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../../../libtool  --tag=CXX   --mode=compile /usr/bin/g++ -DHAVE_CONFIG_H -I. -I../../../../../sst-elements/src/sst/elements/CramSim -I../../../../src    -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/local/module-pkgs/boost/boost-1.56.0-nompi_gcc-4.8.3/include -I/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/local/sst-core/include/sst/core -I/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/local/sst-core/include  -g -O2 -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -MT c_BankStateActive.lo -MD -MP -MF $depbase.Tpo -c -o c_BankStateActive.lo ../../../../../sst-elements/src/sst/elements/CramSim/c_BankStateActive.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /usr/bin/g++ -DHAVE_CONFIG_H -I. -I../../../../../sst-elements/src/sst/elements/CramSim -I../../../../src -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/local/module-pkgs/boost/boost-1.56.0-nompi_gcc-4.8.3/include -I/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/local/sst-core/include/sst/core -I/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/local/sst-core/include -g -O2 -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -MT c_BankStateActive.lo -MD -MP -MF .deps/c_BankStateActive.Tpo -c ../../../../../sst-elements/src/sst/elements/CramSim/c_BankStateActive.cpp  -fPIC -DPIC -o .libs/c_BankStateActive.o
make[5]: *** [c_AddressHasher.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory `/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/devel/trunk/sst-elements-builddir/src/sst/elements/CramSim'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/devel/trunk/sst-elements-builddir/src/sst/elements'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/devel/trunk/sst-elements-builddir/src/sst'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/devel/trunk/sst-elements-builddir/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/jwilso/jenkins/workspace/SST__Autotest_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/819_819/devel/trunk/sst-elements-builddir/src'
make: *** [all-recursive] Error 1
../sqe/buildsys/bamboo.sh : exit failure.

**Comment by mbhealy** [comment]
@allevin 
I've traced the autotester problem to my use of regex. However, I don't have a machine set up to match the autotester configuration, so I have no idea how to debug it. It's working fine on both machine configurations that I have set up. The quickest path to resolution I can think of is to implement my own parser to mimic what I was trying to accomplish. It will take me some time to resolve.

**Comment by allevin** [comment]
@mbhealy 
The sst-test machine is Centos 7.3.  Can you put together a VM that duplicates its setup?

If your changes are going to take some time, I recommend that you close this pull request to stop autotesting.  You can reopen it later when you get closer.  Also we have some in-house tools that can perform testing on your branch to validate your changes before you commit them to a Pull Request.  Just let me know when you want me to run them against your branch.

**Comment by mbhealy** [comment]
@allevin 
I'll work on setting up a VM. Closed for now.

**Pull request closed without merging**
