### PR TITLE
memH: Fix headers for out-of-tree includes.

### PR DESCRIPTION
**Pull request by stkaplan**
This changes includes like "foo.h" to <sst/elements/memHierarchy/foo.h>,
and installs a few that were being skipped.

### CODE REVIEW

**Comment by allevin** [comment]
@stkaplan Here is the build failure...

arielmemmgr_simple.Tpo -c ../../../../../sst-elements/src/sst/elements/ariel/arielmemmgr_simple.cc  -fPIC -DPIC -o .libs/libariel_la-arielmemmgr_simple.o
22:20:39 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
22:20:39 <command-line>:0:0: note: this is the location of the previous definition
22:20:39 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
22:20:39 <command-line>:0:0: note: this is the location of the previous definition
22:20:40 In file included from ../../../../../sst-elements/src/sst/elements/ariel/../Opal/Opal_Event.h:29:0,
22:20:40                  from ../../../../../sst-elements/src/sst/elements/ariel/arielcore.cc:17:
22:20:40 ../../../../../sst-elements/src/sst/elements/ariel/../memHierarchy/memEvent.h:24:44: fatal error: sst/elements/memHierarchy/util.h: No such file or directory
22:20:40  #include <sst/elements/memHierarchy/util.h>
22:20:40                                             ^
22:20:40 compilation terminated.
22:20:40 make[5]: *** [libariel_la-arielcore.lo] Error 1
22:20:40 make[5]: *** Waiting for unfinished jobs....
22:20:41 mv -f .deps/libariel_la-libariel.Tpo .deps/libariel_la-libariel.Plo
22:20:43 mv -f .deps/libariel_la-arielcpu.Tpo .deps/libariel_la-arielcpu.Plo

**Comment by allevin** [comment]
@stkaplan Another build failure:

06:50:56 libtool: compile:  /usr/bin/g++ -DHAVE_CONFIG_H -I. -I../../../../../sst-elements/src/sst/elements/ariel -I../../../../src -DARIEL_TRACE_LIB=/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/239_239/local/sst-elements/lib/sst -DARIEL_TOOL_DIR=/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/239_239/local/sst-elements/libexec -DPINTOOL_EXECUTABLE=/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -I/usr/include/python2.7 -I/usr/include/python2.7 -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/239_239/local/sst-core/include/sst/core -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/239_239/local/sst-core/include -I/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux/source/include -DHAVE_PIN=1 -DPINTOOL_EXECUTABLE=\"/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux/pin.sh\" -DHAVE_SET_PTRACER=1 -I/usr/include/python2.7 -I/usr/include/python2.7 -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/239_239/local/sst-core/include/sst/core -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/239_239/local/sst-core/include -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -MT libariel_la-arielcore.lo -MD -MP -MF .deps/libariel_la-arielcore.Tpo -c ../../../../../sst-elements/src/sst/elements/ariel/arielcore.cc  -fPIC -DPIC -o .libs/libariel_la-arielcore.o
06:50:56 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
06:50:56 <command-line>:0:0: note: this is the location of the previous definition
06:50:56 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
06:50:56 <command-line>:0:0: note: this is the location of the previous definition
06:50:56 In file included from ../../../../../sst-elements/src/sst/elements/ariel/arielcore.cc:17:0:
06:50:56 ../../../../../sst-elements/src/sst/elements/ariel/../Opal/Opal_Event.h:29:48: fatal error: sst/elements/memHierarchy/memEvent.h: No such file or directory
06:50:56  #include <sst/elements/memHierarchy/memEvent.h>
06:50:56                                                 ^
06:50:56 compilation terminated.
06:50:56 make[5]: *** [libariel_la-arielcore.lo] Error 1
06:50:56 make[5]: *** Waiting for unfinished jobs....
06:50:57 mv -f .deps/libariel_la-libariel.Tpo .deps/libariel_la-libariel.Plo

**Comment by stkaplan** [comment]
Whoops, looked like I only fixed the OSX version. I couldn't get ariel/pin building on my machine so I'm kind of stabbing in the dark here...

**Comment by allevin** [comment]
Latest Failure:

00:50:59 libtool: compile:  /usr/bin/g++ -DHAVE_CONFIG_H -I. -I../../../../../sst-elements/src/sst/elements/ariel -I../../../../src -DARIEL_TRACE_LIB=/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/252_252/local/sst-elements/lib/sst -DARIEL_TOOL_DIR=/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/252_252/local/sst-elements/libexec -DPINTOOL_EXECUTABLE=/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -I/usr/include/python2.7 -I/usr/include/python2.7 -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/252_252/local/sst-core/include/sst/core -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/252_252/local/sst-core/include -I/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux/source/include -DHAVE_PIN=1 -DPINTOOL_EXECUTABLE=\"/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux/pin.sh\" -DHAVE_SET_PTRACER=1 -I/usr/include/python2.7 -I/usr/include/python2.7 -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/252_252/local/sst-core/include/sst/core -I/home/jwilso/jenkins/workspace/SST__AutotestGen2_Devel_Branch_Pull_Request_sst-test_sst-elements_withsstcore/252_252/local/sst-core/include -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -MT libariel_la-arielcpu.lo -MD -MP -MF .deps/libariel_la-arielcpu.Tpo -c ../../../../../sst-elements/src/sst/elements/ariel/arielcpu.cc  -fPIC -DPIC -o .libs/libariel_la-arielcpu.o
00:50:59 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
00:50:59 <command-line>:0:0: note: this is the location of the previous definition
00:50:59 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
00:50:59 <command-line>:0:0: note: this is the location of the previous definition
00:50:59 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
00:50:59 <command-line>:0:0: note: this is the location of the previous definition
00:50:59 <command-line>:0:0: warning: "PINTOOL_EXECUTABLE" redefined [enabled by default]
00:50:59 <command-line>:0:0: note: this is the location of the previous definition
00:50:59 In file included from ../../../../../sst-elements/src/sst/elements/ariel/arielcore.cc:17:0:
00:50:59 ../../../../../sst-elements/src/sst/elements/ariel/../Opal/Opal_Event.h:29:48: fatal error: sst/elements/memHierarchy/memEvent.h: No such file or directory
00:50:59  #include <sst/elements/memHierarchy/memEvent.h>
00:50:59                                                 ^
00:50:59 compilation terminated.
00:51:00 make[5]: *** [libariel_la-arielcore.lo] Error 1
00:51:00 make[5]: *** Waiting for unfinished jobs....
00:51:00 ../../../../../sst-elements/src/sst/elements/ariel/libariel.cc:228:21: warning: 'ElementLibraryInfo' is deprecated (declared at

**Comment by stkaplan** [comment]
Everything here is already done in #918

**Pull request closed without merging**
