### PR TITLE
updating miranda goblin HMC-Sim tests to reflect the latest bug fixes …

### PR DESCRIPTION
**Pull request by jleidel**
Updating the GC64 HMC-Sim tests in the miranda test tree in order to take into account the latest bug fixes in the HMC-Sim 3.0 branch.  
---

Instructions for Issuing a Pull Request to sst-elements
-------------------------------------------------------

1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-elements

2 - Verify that Source branch is up to date with the devel branch of sst-elements

3 - After submitting your Pull Request:
   * Automatic Testing will commence in a short while 
      * Pull Requests will be tested with the devel branches of the sst-core and sst-sqe repositories
         * These branches are syncronized with the devel branch of sst-elements.  This is why is it important to keep your source branch up to date.
      * If testing passes, the source branch will be automatically merged (if possible)
         * Pull Requests from forks will not be automatically tested until the code is inspected.
         * Pull Requests from forks will not be automatically merged into the devel branch.
      * If testing fails, You will be notified of the test results.  
         * The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct problems
         
4 - DO NOT DELETE THE BRANCH (OR FORKED REPO) UNTIL THE PULL REQUEST IS MERGED.
----

…in HMC-Sim 3.0+ development

### CODE REVIEW

**Comment by nmhamster** [comment]
@allevin these are approved for testing.

**Comment by allevin** [comment]
Approve Pull Request App - Pull Request Inspected & Approved
allevin Has Inspected and Approved code changes to Pull Request
Comment From allevin = Code inspection done my S. Hammond, and approved.

**Comment by allevin** [comment]
jleidel make sure your branch is up to date with the latest devel branch.

**Comment by jleidel** [comment]
devel merged up to upstream/devel.  apologies for the delay

**Comment by allevin** [comment]
Approve Pull Request App - Pull Request Inspected & Approved
allevin Has Inspected and Approved code changes to Pull Request
Comment From allevin = Remote fork was upgraded to match current devel, code inspection was approved previously by S. Hammond.

**Pull request merged**
