### PR TITLE
New SST-Elements Component to Support GATech HBM Model (using DRAMSim2)

### PR DESCRIPTION
**Pull request by jleidel**
New SST-Elements component to support modified DRAMSim2 model for HBM.  The original HBM model was generated by GATech and is located here: https://github.com/gthparch/HBM
My patches to the HBM repo are currently pending.  The patches provide better interoperability with the HBMDramSim2 model, including SST Statistics support.  This component also requires a duplicate of the pagedMultiBackend component, called "HBMpagedMultiBackend".  This separates the components and prevents us from poisoning the builds when both DRAMSim2 and HBMDRAMSim2 are enabled.      

Adding tests for miranda and memHierarchy, including the required HBMDevice.ini and HBMSystem.ini.  Tracing is enabled in the "memHierarchy.hbmdramsim" component using "backend.tracing" : "1".  Reports request counts, bandwidth and basic latency in the various DRAM queues.  
 
---

Instructions for Issuing a Pull Request to sst-elements
-------------------------------------------------------

1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-elements

2 - Verify that Source branch is up to date with the devel branch of sst-elements

3 - After submitting your Pull Request:
   * Automatic Testing will commence in a short while 
      * Pull Requests will be tested with the devel branches of the sst-core and sst-sqe repositories
         * These branches are syncronized with the devel branch of sst-elements.  This is why is it important to keep your source branch up to date.
      * If testing passes, the source branch will be automatically merged (if possible)
         * Pull Requests from forks will not be automatically tested until the code is inspected.
         * Pull Requests from forks will not be automatically merged into the devel branch.
      * If testing fails, You will be notified of the test results.  
         * The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct problems
         
4 - DO NOT DELETE THE BRANCH (OR FORKED REPO) UNTIL THE PULL REQUEST IS MERGED.
----

### CODE REVIEW

**Comment by allevin** [comment]
Approve Pull Request App - Pull Request Inspected & Approved
allevin Has Inspected and Approved code changes to Pull Request
Comment From allevin = Approve by Si Hammond.

**Comment by hyojongk** [comment]
@nmhamster @jleidel Please let me know if I am wrong. Here's what I think about this change. This change is similar to mine(https://github.com/sstsimulator/sst-elements/pull/713), but I believe it's kind of problematic if one wants to build SST with both DRAMSim2 and HBM model. To avoid the namespace conflict, I recently changed the namespace for the HBM model and made some changes associated with that. With my change, one can build SST with both models (--with-dramsim=<path> --with-hbmsim=<path>) and use either as one wishes, whereas with this change, I believe one should rebuild SST if he/she wants to use DRAMSim2 instead of the HBM model or the other way around.

**Comment by jleidel** [comment]
There appear to be conflicts in the paging logic, but I disagree that your patch is superior.  We would very much like to maintain the backend DRAMSim tracing logic such that we can get useful statistics via the standard SST Statistics mechanisms.  I'll open a bug against this, fork the DRAMSim2 permanently and move on.

**Comment by jleidel** [comment]
Fixes in pull request #718

**Pull request merged**
