### PR TITLE
Simplesim

### PR DESCRIPTION
**Pull request by mfallet**
This creates a new directory inside of sst-elements called "simpleSimulation" with SimpleCarWash being the first set of files inside.  It is based off of the SimpleElementExample directory.

Authors;  Noel Wheeler & Marcel Fallet

Instructions for Issuing a Pull Request to sst-elements
-------------------------------------------------------

1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-elements

2 - Verify that Source branch is up to date with the devel branch of sst-elements

3 - After submitting your Pull Request:
   * Automatic Testing will commence in a short while 
      * Pull Requests will be tested with the devel branches of the sst-core and sst-sqe repositories
         * These branches are syncronized with the devel branch of sst-elements.  This is why is it important to keep your source branch up to date.
      * If testing passes, the source branch will be automatically merged (if possible)
         * Pull Requests from forks will not be automatically tested until the code is inspected.
         * Pull Requests from forks will not be automatically merged into the devel branch.
      * If testing fails, You will be notified of the test results.  
         * The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct problems
         
4 - DO NOT DELETE THE BRANCH (OR FORKED REPO) UNTIL THE PULL REQUEST IS MERGED.
----

### CODE REVIEW

**Comment by bjmoor** [comment]
Hi Marcel,

  Can you change this PR to target the 'devel' branch, rather than master?

Thanks!

**Comment by mfallet** [comment]
Hey Branden,

Sorry about the confusion, I've edited the pull request to go to devel instead of master.  My fault, sorry!

**Comment by nmhamster** [comment]
@bjmoor can you please re-review the code for the changes you requested?

**Comment by mfallet** [comment]
Branden,

This should be fixed now.  Thanks!

**Comment by nmhamster** [comment]
@allevin will the auto-tester begin to process this now @bjmoor has marked it for approval?

**Comment by mfallet** [comment]
Thanks for pushing through this and your patience Branden and Si.  Much appreciated!

**Comment by allevin** [comment]
Approve Pull Request App - Pull Request Inspected & Approved
allevin Has Inspected and Approved code changes to Pull Request
Comment From allevin = Code inspected and approved by B. Moore

**Comment by allevin** [comment]
mfallet, 

Can you verify that the simplesim branch in your fork up to date with the lastest devel branch of sst-elements?  See step 2 at the top of these comments.  The failures look like your branch is way behind our devel branch.

**Comment by mfallet** [comment]
Branden / Si / Aaron,

I /believe/ I have merged the simplesim branch with the latest devel changes.  Please let me know if you don't see them.

Thanks!

**Comment by bjmoor** [comment]
@allevin can you re-release this branch for testing?

**Comment by allevin** [comment]
Approve Pull Request App - Pull Request Inspected & Approved
allevin Has Inspected and Approved code changes to Pull Request
Comment From allevin = mfallet updated branch, approved for testing by B. Moore.

**Pull request merged**
