### PR TITLE
Add io redirect functionality to Ariel

### LINKED ISSUE #1856: Ariel does not support IO redirection
Ariel does not IO redirection, meaning benchmarks that accept their input from stdin, such as some of the benchmarks in SPEC CPU, cannot be run.

### PR DESCRIPTION
**Pull request by plavin**
These changes add the ability to do IO redirection for the traced Ariel process. 

The changes to the Ariel interface allow the user to specify files for stdin, stdout, and stderr. Additionally, they can specify whether they want to append or overwrite the files that used for stdout and stderr. 

This is marked draft as I haven't written unit tests. I would appreciate any feedback.

Fixes #1856.

### CODE REVIEW

**Review by gvoskuilen — APPROVED** [review]
Thanks @plavin . Looks good.

**Comment by hughes-c** [comment]
@plavin What's the status of this?

**Comment by plavin** [comment]
@hughes-c This code works but there are no test cases in the PR yet.

**Comment by plavin** [comment]
I'll work on completing this this week.

**Comment by plavin** [comment]
The logic in the testsuite needs a bit of cleanup but this is nearly complete now.

**Review by gvoskuilen — APPROVED** [review]

**Review by gvoskuilen — APPROVED** [review]

**Pull request merged**
