### PR TITLE
modified 'handling mmap requests in opal' commit

### PR DESCRIPTION
**Pull request by VamseeReddyK**

### CODE REVIEW

**Comment by VamseeReddyK** [comment]
@allevin Do I have to create another pull request to merge sstsimulator:disagg_amro branch with my forked disagg_amro branch(VamseeReddyK:disagg_amro)?

**Comment by allevin** [comment]
@VamseeReddyK you need to work in your fork from this point moving forward.  You can create PR's to merge from your fork into sstsimulator:sst-elements/devel (like you just did).  We will not accept PR's into any other branch.  You do not need to create a PR to go from the sst-elements repo to your fork, you can do that using git remotes and merge/pulls.

Your PR's must be inspected and approved by a team member before being tested and merged.

**Comment by allevin** [comment]
@VamseeReddyK There was a lot of changes to golden files for tests in the past few days.  That is what is causing the failures.  You need to merge the devel branch into your fork and get up to date so the test system has the correct data to check against.

**Comment by allevin** [comment]
@VamseeReddyK I am turning on the WIP label.  I will remove it when you update your PR.

**Pull request closed without merging**
