### PR TITLE
Afrodri/gensa

### PR DESCRIPTION
**Pull request by afrodri**
Commit of the GeNSA component. Tests are in :
sst-elements/src/sst/elements/GNA/tests

### CODE REVIEW

**Comment by afrodri** [comment]
Test files were renamed, need to change the test scripts.

**Comment by hughes-c** [comment]
@afrodri 

- Reference file in SQE is test.ref.out
- Need to set debug to '0' in comp_memory to match reference when running test.py

**Comment by hughes-c** [comment]
@afrodri  Turning off verbose in the GNA component changes results significantly

**Comment by hughes-c** [comment]
@afrodri @jpvandy There are two tests in the GNA folder but only one is being run.

**Comment by allevin** [comment]
@afrodri Is this PR still valid? it is over 6 months old...

**Pull request closed without merging**
