### PR TITLE
Merge pull request from sstsimulator/sst-elements devel

### PR DESCRIPTION
**Pull request by derrickgreenspan**
This pull requests adds the flush and fence features to ariel.

### CODE REVIEW

**Comment by derrickgreenspan** [comment]
I'm new to merge requests - I"m not sure how to tag a merge request as new-feature, though

**Comment by allevin** [comment]
@derrickgreenspan Hi Derrick, Here is the general sequence for Pull Requests (PR).  Since you are an outside user, your code must be inspected by a member of the team before testing will commence.  Once its inspected, the Autotester will automatically test your pull request with the devel branches of appropriate repos (SST-Core).  Once that test completes, the PR must have a final approval before being merged.  It can take a few days for people to become available.  The most important thing is to ensure that your forked/branch is up to date with the **devel** branch from sst-elements.  This ensures that you are running the latest code.  If you have test errors and/or you make changes to your branch, the whole process must re-start.  

Also, since you are not a member of the project, you cannot modify labels but don't worry about that.

**Comment by allevin** [comment]
Marking PR as WIP until autotester issues are resolved.  I will remove the WIP flag.

**Comment by allevin** [comment]
@derrickgreenspan Derrick, @gvoskuilen has to re-review your changes before it can be tested.  Once its approved, the autotester will run.  If it passes, you just need to wait for someone on the team to merge it.  If it fails, I can send you the information relating to the failure.

In the future you should put an `@<username>` mention in your comments.  Many people have email filters that prioritize messages that come in with their name mentioned.

**Comment by derrickgreenspan** [comment]
@allevin - understood. I will wait for @gvoskuilen to review and accept the changes.

Thank you! Sorry for all the confusion.

**Comment by allevin** [comment]
@derrickgreenspan No problem at all.  Thanks for contributing to the project...

**Comment by derrickgreenspan** [comment]
@gvoskuilen , these changes have been made. Hopefully all is good now.

Thanks

**Comment by allevin** [comment]
@gvoskuilen This PR has passed, but it requires someone on the team to merge it (and provide a final inspection).

**Comment by allevin** [comment]
@derrickgreenspan Congrats, your PR was merged into the devel branch.

**Comment by derrickgreenspan** [comment]
Excellent! Thank you!


________________________________

**Pull request merged**
